Vagrant.configure("2") do |config|
    config.vm.box = "packer_ubuntu-example1_virtualbox_amd64.box"
    config.ssh.insert_key = false
    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"
end